document.writeln("        <div class=\'sign_in\' id=\'sign_in\'>");
document.writeln("            <div class=\'sign_in_bg\'></div>");
document.writeln("            <div class=\'loging_in\'>");
document.writeln("                <div class=\'loging_in_bar\'>");
document.writeln("                    Sign In");
document.writeln("                    <a id=\'closs_motai\' href=\'javascript:void(0)\'></a>");
document.writeln("                </div>");
document.writeln("                <div class=\'sign_warn\'>");
document.writeln("                        <p>Incorrect email address or password. Please try again.</p>");
document.writeln("                        Make sure the Caps Lock is off before you enter password.");
document.writeln("                </div>");
document.writeln("                <ul>");
document.writeln("                    <li>Email<br/>");
document.writeln("                        <input class=\'sign_accountNumber\' type=\'text\'/>");
document.writeln("                    </li>");
document.writeln("");
document.writeln("                    <li>Password<br/>");
document.writeln("                        <input class=\'sign_password\' type=\'password\'/>");
document.writeln("                    </li>");
document.writeln("                    <li>Forgot your <a class=\'FYPW\' href=\'./forgot.html\'>password</a>?</li>");
document.writeln("                    <li><input id=\'SSI\' type=\'checkbox\'/>Stay signed in <br/>");
document.writeln("                        <span>Protect your privacy - sign out when you\'re done.</span>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("                <div class=\'loging_in_denglu\'>");
document.writeln("                    <input type=\'button\' value=\'Sign in\'/>");
document.writeln("                    <button><a href=\'./join-free.html\'>Join Free</a></button>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");